server:
  port: 9002

spring:
  application:
    name: uaa
  main:
    cloud-platform: kubernetes
  profiles:
    active: local
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        register:
          enabled: true
          host: 192.168.0.28 # 本机ip
          port: ${server.port}
          service-id: ${spring.application.name}
          namespace: ${spring.cloud.kubernetes.client.namespace}
          metadata:
            namespace: ${spring.cloud.kubernetes.client.namespace}
            name: ${spring.application.name}
      loadbalancer:
        mode: POD # 使用 pod 方式
        port-name: server # service port 名称
      client:
        namespace: spring-cloud-k8s
    discovery:
      blocking:
        enabled: true
      enabled: true

proxy:
  config:
    host: apisix.proxy.cc
    port: 31684
    k8s-net-prefix: 10.1;10.244
