spring:
  application:
    name: uaa
  profiles:
    active: test
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      loadbalancer:
        mode: service

server:
  port: 9002