apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud-k8s
  name: account
  labels:
    app: account
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      name: server
      targetPort: 8080
  selector:
    app: account