spring:
  main:
    web-application-type: NONE

cache.config:
  expired: ${APISIX_CONF_EXPIRE_TIME:10000}
  capacity: 1000

socket:
  file: ${APISIX_LISTEN_ADDRESS:/dev/shm/apisix.sock}

logging:
  level:
    org.apache.apisix.plugin.runner.HttpResponse: warn