spring:
  application:
    name: coordinator
  main:
    web-application-type: NONE
    cloud-platform: kubernetes
  profiles:
    active: local
  cloud:
    kubernetes:
      discovery:
        enabled: true # 开启服务发现
        register:
          enabled: false
        catalog-services-watch:
          enabled: true
        all-namespaces: false
      loadbalancer:
        mode: POD #使用 pod 方式
        enabled: true #开启kubernetes 服务负载均衡
      client:
        namespace: spring-cloud-k8s
    discovery:
      blocking:
        enabled: true
      enabled: true
      client:
        health-indicator:
          enabled: false
    refresh:
      enabled: false

proxy:
  config:
    k8s-net-prefix: 10.1;10.244

cache.config:
  expired: ${APISIX_CONF_EXPIRE_TIME:10000}
  capacity: 1000

socket:
  file: ${APISIX_LISTEN_ADDRESS:/opt/apisix/apisix.sock}

filter:
  test:
    enabled: true

logging:
  level:
    org.apache.apisix.plugin.runner.HttpResponse: warn