spring:
  application:
    name: coordinator
  main:
    web-application-type: NONE
  profiles:
    active: test
  cloud:
    kubernetes:
      enabled: true #开启kubernetes
      discovery:
        enabled: true # 开启服务发现
        register: false
        catalog-services-watch:
          enabled: true
        all-namespaces: false
      loadbalancer:
        enabled: true #开启kubernetes 服务负载均衡
        mode: POD #使用 pod 方式
      client:
        namespace: spring-cloud-k8s
    discovery:
      enabled: true
    loadbalancer:
      enabled: true

proxy:
  config:
    k8s-net-prefix: 10.1;10.244

cache.config:
  expired: ${APISIX_CONF_EXPIRE_TIME:10000}
  capacity: 1000

socket:
  file: ${APISIX_LISTEN_ADDRESS:/opt/apisix/apisix.sock}

filter:
  test:
    enabled: true

logging:
  level:
    org.apache.apisix.plugin.runner.HttpResponse: warn