kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisix
  namespace: wxl-spring-cloud-k8s
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.15.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: apisix
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/name: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
            defaultMode: 420
        - name: jar-volume
          emptyDir: { }
        - name: coordinator-class-cache
          hostPath:
            path: /tmp/coordinator-class-cache
            type: DirectoryOrCreate
        - name: apisix-socket
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
          command:
            - sh
            - '-c'
            - >-
              until nc -z etcd.wxl-spring-cloud-k8s.svc.cluster.local 2379; do echo
              waiting for etcd `date`; sleep 2; done;
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: nvriot-biz-coordinator
          image: app:latest
          imagePullPolicy: IfNotPresent
          command:
            - cp
            - /tmp/spring-cloud-kubernetes-coordinator-0.0.1.jar
            - /app/spring-cloud-kubernetes-coordinator-0.0.1.jar
          volumeMounts:
            - mountPath: /app
              name: jar-volume
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
      containers:
        - name: apisix
          image: apache/apisix:2.15.0-alpine
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
            - name: apisix-socket
              mountPath: /dev/shm
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - image: 221.214.10.82:81/base/ibm-semeru-runtimes:open-17.0.3_7-jdk
          name: coordinator
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          command:
            - "java"
          args:
            - "-Xshareclasses:name=coordinator,cacheDir=/class-cache,nonfatal,persistent,verbose"
            - "-XX:+UseContainerSupport"
            - "-XX:InitialRAMPercentage=95.0"
            - "-XX:MaxRAMPercentage=95.0"
            - "-XX:+HeapDumpOnOutOfMemoryError"
            - "-XX:HeapDumpPath=./dump-%t.hprof"
            - "-XX:+UnlockDiagnosticVMOptions"
            - "-XX:+UnlockExperimentalVMOptions"
            - "-XX:-OmitStackTraceInFastThrow"
            - "-Xlog:gc*=debug:file=./gc-%t.log:utctime,level,tags:filecount=10,filesize=100M"
            - "-Xlog:jit+compilation=info:file=./jit_compile-%t.log:utctime,level,tags:filecount=10,filesize=10M"
            - "-Xlog:safepoint=debug:file=./safepoint-%t.log:utctime,level,tags:filecount=10,filesize=10M"
            - "-XX:+DisableExplicitGC"
            - "-XX:GuaranteedSafepointInterval=0"
            - "-XX:+UseCountedLoopSafepoints"
            - "-XX:StartFlightRecording=disk=true,maxsize=4096m,maxage=3d"
            - "-XX:FlightRecorderOptions=maxchunksize=128m"
            - "--add-opens"
            - "java.base/java.lang=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.io=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.lang.invoke=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.lang.reflect=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.text=ALL-UNNAMED"
            - "--add-opens"
            - "java.desktop/java.awt.font=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.math=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.net=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.nio=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.security=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.text=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.time=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/java.util=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/jdk.internal.access=ALL-UNNAMED"
            - "--add-opens"
            - "java.base/jdk.internal.misc=ALL-UNNAMED"
            - "-Dserver.port=8080"
            - "-Dspring.profiles.active=dev"
            - "-Duser.timezone=GMT+08"
            - "-Dfile.encoding=UTF-8"
            - "-Djava.security.egd=file:/dev/./urandom"
            - "-Dsocket.file=/dev/shm/apisix.sock"
            - "-Dnetworkaddress.cache.ttl=10"
            - "-jar"
            - "/app/spring-cloud-kubernetes-coordinator-0.0.1.jar"
          env:
            - name: LANG
              value: "zh_CN.UTF-8"
            - name: user.language
              value: "zh"
            - name: user.region
              value: "CN"
          volumeMounts:
            - mountPath: /app
              name: jar-volume
            - name: coordinator-class-cache
              mountPath: /class-cache
            - name: apisix-socket
              mountPath: /dev/shm
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
#      nodeName: k8s-node06-8-218
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

